// <auto-generated />
using System;
using MedView.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedView.Server.Migrations
{
    [DbContext(typeof(DicomDbContext))]
    [Migration("20260117184839_InitialMySqlMigration")]
    partial class InitialMySqlMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MedView.Server.Models.Annotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<double?>("FontSize")
                        .HasColumnType("double");

                    b.Property<int?>("FrameNumber")
                        .HasColumnType("int");

                    b.Property<int>("InstanceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PositionData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId");

                    b.ToTable("Annotations");
                });

            modelBuilder.Entity("MedView.Server.Models.HangingProtocol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyPart")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LayoutConfig")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Modality")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Modality", "BodyPart");

                    b.ToTable("HangingProtocols");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 17, 18, 48, 39, 46, DateTimeKind.Utc).AddTicks(805),
                            Description = "Default layout for CT studies",
                            IsActive = true,
                            IsDefault = true,
                            LayoutConfig = "{\n                    \"rows\": 1,\n                    \"columns\": 1,\n                    \"viewports\": [\n                        {\"position\": 0, \"seriesIndex\": 0}\n                    ]\n                }",
                            Modality = "CT",
                            Name = "CT Default",
                            Priority = 100
                        },
                        new
                        {
                            Id = 2,
                            BodyPart = "HEAD",
                            CreatedAt = new DateTime(2026, 1, 17, 18, 48, 39, 46, DateTimeKind.Utc).AddTicks(808),
                            Description = "Multi-sequence brain MRI layout",
                            IsActive = true,
                            IsDefault = false,
                            LayoutConfig = "{\n                    \"rows\": 2,\n                    \"columns\": 2,\n                    \"viewports\": [\n                        {\"position\": 0, \"seriesDescription\": \"T1\"},\n                        {\"position\": 1, \"seriesDescription\": \"T2\"},\n                        {\"position\": 2, \"seriesDescription\": \"FLAIR\"},\n                        {\"position\": 3, \"seriesDescription\": \"DWI\"}\n                    ]\n                }",
                            Modality = "MR",
                            Name = "MR Brain",
                            Priority = 90
                        },
                        new
                        {
                            Id = 3,
                            BodyPart = "CHEST",
                            CreatedAt = new DateTime(2026, 1, 17, 18, 48, 39, 46, DateTimeKind.Utc).AddTicks(811),
                            Description = "Side-by-side comparison for chest X-rays",
                            IsActive = true,
                            IsDefault = false,
                            LayoutConfig = "{\n                    \"rows\": 1,\n                    \"columns\": 2,\n                    \"viewports\": [\n                        {\"position\": 0, \"studyIndex\": 0, \"seriesIndex\": 0},\n                        {\"position\": 1, \"studyIndex\": 1, \"seriesIndex\": 0}\n                    ],\n                    \"enablePriorComparison\": true\n                }",
                            Modality = "CR",
                            Name = "Chest X-Ray Comparison",
                            Priority = 80
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 17, 18, 48, 39, 46, DateTimeKind.Utc).AddTicks(813),
                            Description = "Standard mammography display",
                            IsActive = true,
                            IsDefault = false,
                            LayoutConfig = "{\n                    \"rows\": 2,\n                    \"columns\": 2,\n                    \"viewports\": [\n                        {\"position\": 0, \"viewPosition\": \"MLO\", \"laterality\": \"R\"},\n                        {\"position\": 1, \"viewPosition\": \"MLO\", \"laterality\": \"L\"},\n                        {\"position\": 2, \"viewPosition\": \"CC\", \"laterality\": \"R\"},\n                        {\"position\": 3, \"viewPosition\": \"CC\", \"laterality\": \"L\"}\n                    ]\n                }",
                            Modality = "MG",
                            Name = "Mammography",
                            Priority = 95
                        });
                });

            modelBuilder.Entity("MedView.Server.Models.Instance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BitsAllocated")
                        .HasColumnType("int");

                    b.Property<int?>("BitsStored")
                        .HasColumnType("int");

                    b.Property<int?>("Columns")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<double?>("FrameTime")
                        .HasColumnType("double");

                    b.Property<int?>("HighBit")
                        .HasColumnType("int");

                    b.Property<string>("ImageOrientationPatient")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ImagePositionPatient")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("InstanceNumber")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfFrames")
                        .HasColumnType("int");

                    b.Property<string>("PhotometricInterpretation")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PixelRepresentation")
                        .HasColumnType("longtext");

                    b.Property<string>("PixelSpacing")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<double?>("RescaleIntercept")
                        .HasColumnType("double");

                    b.Property<double?>("RescaleSlope")
                        .HasColumnType("double");

                    b.Property<int?>("Rows")
                        .HasColumnType("int");

                    b.Property<int?>("SamplesPerPixel")
                        .HasColumnType("int");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.Property<double?>("SliceLocation")
                        .HasColumnType("double");

                    b.Property<string>("SopClassUid")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SopInstanceUid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("TransferSyntaxUid")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<double?>("WindowCenter")
                        .HasColumnType("double");

                    b.Property<double?>("WindowWidth")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.HasIndex("SopInstanceUid")
                        .IsUnique();

                    b.ToTable("Instances");
                });

            modelBuilder.Entity("MedView.Server.Models.Measurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Area")
                        .HasColumnType("double");

                    b.Property<string>("Color")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("FrameNumber")
                        .HasColumnType("int");

                    b.Property<int>("InstanceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<double?>("Max")
                        .HasColumnType("double");

                    b.Property<double?>("Mean")
                        .HasColumnType("double");

                    b.Property<double?>("Min")
                        .HasColumnType("double");

                    b.Property<string>("PositionData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double?>("StdDev")
                        .HasColumnType("double");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Unit")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<double?>("Value")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("MedView.Server.Models.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyPartExamined")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("Columns")
                        .HasColumnType("int");

                    b.Property<string>("ImageOrientationPatient")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Modality")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("NumberOfInstances")
                        .HasColumnType("int");

                    b.Property<string>("ProtocolName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Rows")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SeriesDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SeriesDescription")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SeriesInstanceUid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SeriesNumber")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("SeriesTime")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<double?>("SliceThickness")
                        .HasColumnType("double");

                    b.Property<double?>("SpacingBetweenSlices")
                        .HasColumnType("double");

                    b.Property<int>("StudyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Modality");

                    b.HasIndex("SeriesInstanceUid")
                        .IsUnique();

                    b.HasIndex("StudyId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("MedView.Server.Models.Study", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessionNumber")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InstitutionName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NumberOfInstances")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfSeries")
                        .HasColumnType("int");

                    b.Property<string>("PatientAge")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime?>("PatientBirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PatientId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PatientName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PatientSex")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("ReferringPhysicianName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("StudyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StudyDescription")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StudyId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("StudyInstanceUid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("StudyTime")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("AccessionNumber");

                    b.HasIndex("PatientId");

                    b.HasIndex("PatientName");

                    b.HasIndex("StudyDate");

                    b.HasIndex("StudyInstanceUid")
                        .IsUnique();

                    b.ToTable("Studies");
                });

            modelBuilder.Entity("MedView.Server.Models.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnnotationColor")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("DefaultLayout")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("DefaultTool")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("DefaultWindowPresets")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MeasurementColor")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("ShowAnnotations")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ShowMeasurements")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ShowOverlay")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnnotationColor = "#00FF00",
                            DefaultLayout = "1x1",
                            DefaultTool = "wwwc",
                            DefaultWindowPresets = "[\n                    {\"name\": \"CT Abdomen\", \"wc\": 40, \"ww\": 400},\n                    {\"name\": \"CT Bone\", \"wc\": 500, \"ww\": 2000},\n                    {\"name\": \"CT Brain\", \"wc\": 40, \"ww\": 80},\n                    {\"name\": \"CT Chest\", \"wc\": -600, \"ww\": 1500},\n                    {\"name\": \"CT Lung\", \"wc\": -400, \"ww\": 1500}\n                ]",
                            LastUpdated = new DateTime(2026, 1, 17, 18, 48, 39, 46, DateTimeKind.Utc).AddTicks(963),
                            MeasurementColor = "#FFFF00",
                            ShowAnnotations = true,
                            ShowMeasurements = true,
                            ShowOverlay = true,
                            UserId = "default"
                        });
                });

            modelBuilder.Entity("MedView.Server.Models.Annotation", b =>
                {
                    b.HasOne("MedView.Server.Models.Instance", "Instance")
                        .WithMany("Annotations")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("MedView.Server.Models.Instance", b =>
                {
                    b.HasOne("MedView.Server.Models.Series", "Series")
                        .WithMany("Instances")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MedView.Server.Models.Measurement", b =>
                {
                    b.HasOne("MedView.Server.Models.Instance", "Instance")
                        .WithMany("Measurements")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("MedView.Server.Models.Series", b =>
                {
                    b.HasOne("MedView.Server.Models.Study", "Study")
                        .WithMany("Series")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("MedView.Server.Models.Instance", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("MedView.Server.Models.Series", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("MedView.Server.Models.Study", b =>
                {
                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
